-- Targeted overrides for domains that need PDF-aligned template content.

DELETE FROM vbmapp_program_templates
WHERE vbmapp_domain IN ('Listener Responding', 'Independent Play');

INSERT INTO vbmapp_program_templates
  (vbmapp_domain, data_collection, prerequisite_skills, materials, sd,
   correct_responses, incorrect_responses, prompting_hierarchy, prompting_hierarchy_detail,
   error_correction, transfer_procedure, reinforcement_schedule, generalization_plan, maintenance_plan)
VALUES
('Listener Responding',
 'Use trial-by-trial data for listener discriminations and timed probes for attending and orienting targets. Track independent, prompted, and incorrect responses across responding to name, identifying familiar people/reinforcers, array selections, motor-action commands, noun-verb directions, and 3-step directions. After mastery in structured teaching, probe the same targets in books, picture scenes, and natural environments.',
 'Child attends to speech sounds, tolerates brief teaching, and can orient to adults, preferred people, or highly reinforcing items. Early targets may begin with own name, favorite people, favorite characters, and simple motor commands. Later targets require scanning messy arrays, performing actions without visual prompts, and responding to increasingly complex verbal instructions.',
 'Family member and character pictures, photos of familiar people and pets, common objects, body-part targets, books, scene pictures, and natural-environment arrays. Include materials for motor-action commands, color and shape targets, items for prepositions and pronouns, and sets of similar items for adjective/adverb discriminations.',
 '"Look at me," name call, "Where''s __?," "Show me __," "Touch __," and action directions such as "jump," "clap," or "get your coat, hang it up, and sit down." Progress from single-word listener discriminations to noun-verb directions, book/scene searches, color-shape combinations, prepositions, pronouns, relative adjectives/adverbs, and 3-step directions.',
 'Child orients to the speaker, responds to name, looks at/touches/points to the correct item, performs the named action, or follows the full spoken direction without visual prompts. Responses should be clearly controlled by the spoken words and not by position, visual cueing, or scrolling.',
 'No orientation/response, wrong item, wrong action, position responding, scrolling through the array, or reliance on visual prompts or repeated cues. For multi-step directions, omitting, reordering, or stopping after only part of the direction also counts as incorrect.',
 'most_to_least',
 'Use only the minimum visual support needed after the spoken SD: full physical guidance if necessary, then partial physical, gestural/point, model the action, and finally independent responding. Fade prompts quickly so the spoken word becomes the controlling variable, especially for responding to name, array selections, and motor-action directions.',
 'Re-present the SD, block errors from contacting reinforcement, guide the correct response, label the target, and then re-probe without the prompt. Insert known easy listener trials between re-probes. For multi-step directions, restart the whole chain or re-teach the missed step(s) immediately, then probe again.',
 'Build from highly reinforcing and familiar targets to less salient items: own name -> favorite people/reinforcers -> array of 2/4 -> messy arrays of 6/8 -> books/scenes/natural environment. Move from simple motor commands to specific actions, then noun-verb directions, then color/shape, prepositions/pronouns, relative adjectives/adverbs, and finally 3-step directions.',
 'Use dense reinforcement for correct independent listener responding early, especially when conditioning attention to speech and name response. Reinforce prompted responses more lightly, then fade toward social praise, access to ongoing activities, and naturally occurring consequences during play, books, routines, and classroom directions.',
 'Teach across adults, rooms, books, materials, and natural daily routines. Vary array position, messy vs. neat layouts, multiple examples of the same item, and whether targets appear in books, picture scenes, or the natural environment. Program listener skills during play, dressing, snack, cleanup, playground routines, and peer/group contexts.',
 'Embed mastered listener targets throughout the day. Re-probe responding to name, familiar people, motor commands, book/scene vocabulary, and multi-step directions during normal routines. Expand the listener repertoire continuously so it stays balanced with tact, mand, LRFFC, and social-language development.'),
('Independent Play',
 'Use timed observations in 30-minute samples and frequency notes for play variety. Track duration of independent object play, movement play, cause-and-effect play, playground play, arts/crafts, sustained leisure, and workbook/pre-academic play. Also note novel play, pretend play, searching for missing parts, assembling sets, and repeated attempts to improve an effect.',
 'Child shows some interest in toys, movement, or objects and can tolerate reduced adult interaction. Earlier targets may begin with simple manipulation/exploration or cause-and-effect play. Later targets require using toys by function, assembling multi-part sets, creative play, pretend play, arts/crafts, and sustained leisure without adult reinforcement.',
 'Preferred toys, common household items, cause-and-effect toys, pop-up toys, containers, pull toys, playground equipment, multi-part toy sets, pretend-play props, costumes, dolls, art supplies, blocks/Legos, Etch-A-Sketch-type materials, and pre-academic activity books. Include novel play areas and everyday items that can be used creatively.',
 'Arrange a rich play environment and minimize unnecessary adult prompts. Use occasional starter statements only when needed, such as "Let''s see what you can play with," "Find what''s missing," or a brief model of a new play action. Then fade back so play is maintained by the materials and activities themselves.',
 'Child independently manipulates and explores objects, varies activities, generalizes play in novel settings, engages in movement or cause-and-effect play, searches for missing parts, uses toys by function, plays creatively, uses playground equipment, assembles sets, pretends, repeats actions to get a better effect, engages in arts/crafts, sustains play, or works in pre-academic activity books without adult mediation.',
 'No play, very brief contact only, repetitive nonfunctional/stereotypy with materials, immediate adult-attention seeking that replaces play, abandoning materials before target duration, or using toys in ways unrelated to the teaching goal when functional/creative play is being targeted.',
 'least_to_most',
 'Start with environment arrangement and wait time. If needed, add a gestural cue, brief verbal suggestion, short model, then light physical guidance to start the play action. Fade adult proximity, prompts, and commentary quickly so play remains independent and automatically reinforcing.',
 'Use brief neutral redirection back to materials, model the functional or pretend action once, and immediately withdraw attention. Reset the play setup when parts are missing or materials are misused. Avoid turning independent-play teaching into continuous adult-led play.',
 'Move from simple object exploration -> play variety -> novel setting play -> movement play -> cause-and-effect play. Then add missing-part searches, toy function, creative use of everyday items, playground equipment, and assembling multi-part sets. For advanced play, transfer to pretend play, repeated attempts to improve gross motor outcomes, arts/crafts, sustained leisure, and pre-academic activity books.',
 'Let the activity itself become the main reinforcer whenever possible. Early on, pair play with brief social praise, access to interesting materials, and short check-ins. Thin adult-delivered reinforcement as duration, variety, creativity, and independence grow.',
 'Rotate toys and settings, include new playrooms and playgrounds, and program across home, clinic, school, outdoors, and community leisure spaces. Teach with commercial toys and everyday items, and vary materials so play does not remain tied to one set or one script. Generalize to solo play, side-by-side play, and peer-ready play themes such as pretend cooking or building.',
 'Keep a broad play menu available and revisit mastered play types weekly. Probe duration, novelty, pretend play, arts/crafts, and pre-academic leisure over time. Add new activities as interests change so independent play remains functional, age-appropriate, and supportive of later social play.');
