-- VB-MAPP Domain-Level Program Plan Templates
-- One row per VB-MAPP clinical domain (16 domains)
-- These templates provide evidence-based defaults for the 12 program plan fields.

CREATE TABLE IF NOT EXISTS vbmapp_program_templates (
  id                       SERIAL PRIMARY KEY,
  vbmapp_domain            VARCHAR(100) UNIQUE NOT NULL,
  data_collection          TEXT,
  prerequisite_skills      TEXT,
  materials                TEXT,
  sd                       TEXT,
  correct_responses        TEXT,
  incorrect_responses      TEXT,
  prompting_hierarchy      VARCHAR(20) DEFAULT 'most_to_least',
  prompting_hierarchy_detail TEXT,
  error_correction         TEXT,
  transfer_procedure       TEXT,
  reinforcement_schedule   TEXT,
  generalization_plan      TEXT,
  maintenance_plan         TEXT
);

-- Remove existing rows so this file is idempotent
DELETE FROM vbmapp_program_templates;

INSERT INTO vbmapp_program_templates
  (vbmapp_domain, data_collection, prerequisite_skills, materials, sd,
   correct_responses, incorrect_responses, prompting_hierarchy, prompting_hierarchy_detail,
   error_correction, transfer_procedure, reinforcement_schedule, generalization_plan, maintenance_plan)
VALUES

-- ── MAND ─────────────────────────────────────────────────────────────────────
('Mand',
 'Frequency count of unprompted (spontaneous) mands per session. Record prompted vs. unprompted separately on a tally sheet. Target: 20+ unprompted mands per 30-minute session.',
 'Motivating operations (MOs) identified via preference assessment; attends to presented items for at least 3 seconds; has at least one functional response form (vocal approximation, sign, or AAC/icon exchange).',
 'High-preference items and activities identified through formal preference assessment (e.g., paired-stimulus, multiple-stimulus without replacement). Variety of food, toy, and activity reinforcers. Capture naturally occurring MOs throughout the day.',
 'Motivating operation (MO) is in effect — child is deprived of a desired item/activity. Therapist withholds or creates a need for the item. No verbal prompt given; wait 5 seconds for spontaneous mand. Use "What do you want?" only after 5-second wait if needed.',
 'Child emits a mand (vocal word, approximation, sign, or AAC selection) for the desired item within 5 seconds, without a verbal prompt from the therapist.',
 'No response within 5 seconds, incorrect/unrelated mand, use of inappropriate behavior to request, or required verbal prompt beyond "What do you want?"',
 'least_to_most',
 '1. Time delay (5-second wait with expectant look) → 2. Partial verbal prompt (first sound/syllable of target word) → 3. Full verbal model ("Say ___") → 4. Sign prompt or AAC model if using augmentative communication → 5. Physical guidance (only if necessary for AAC selection). Fade prompts across sessions.',
 'If incorrect or no response: provide immediate full verbal model (echoic prompt). Reinforce correct imitation with brief access to item (1–2 seconds). Do NOT deliver the full reinforcer for prompted mands during acquisition. Insert 1–2 "easy" mand trials, then re-present target.',
 'Begin with echoic prompt immediately followed by reinforcer delivery. Systematically fade: full echoic → partial echoic → time delay only → spontaneous. Transfer control from therapist prompts to the child''s natural MOs. Practice in 3+ natural settings daily (home, school, community).',
 'CRF (1:1 reinforcement ratio) during acquisition — deliver the actual requested item immediately after every correct mand. Thin to VR2 after 5 consecutive sessions at 80%+ correct unprompted. Progress to VR3–VR5 as manding becomes fluent.',
 'Teach mands across: 3+ different therapists/adults, 3+ settings (therapy room, home, classroom, community), and 3+ different examples of each reinforcer (e.g., different brands of preferred snack). Conduct generalization probe trials monthly.',
 'Monthly probe trials across all mastered mands and novel settings. If performance drops below 80%, re-enter acquisition with brief errorless teaching sessions. Build mand repertoire across all daily routines. Document mand rate growth over time.'),

-- ── TACT ─────────────────────────────────────────────────────────────────────
('Tact',
 'Discrete trial format — record correct (C), incorrect (I), or prompted (P) on each trial. Calculate % correct per session from at least 10 trials. Mastery criterion: 80%+ independent over 3 consecutive sessions per item.',
 'Basic matching-to-sample (VP/MTS Level 1–2); attends to stimuli for 3+ seconds; has echoic or imitative ability to approximate target labels; basic listener responding for a few items.',
 'Real objects, photographs, and picture cards of common items (animals, vehicles, food, body parts, household objects, people). Vocabulary lists organized by category. 3D objects for higher-level tacting. Picture books for naturalistic tact opportunities.',
 'Therapist presents object or picture and asks "What is this?" — or holds up item and waits (for spontaneous tact targets). Array of one item during initial acquisition. Vary stimuli to prevent rote responding.',
 'Child labels the item within 5 seconds without a verbal prompt. Approximations accepted during early acquisition if the response is clearly discriminative from other items and improving toward the target form.',
 'No response within 5 seconds, incorrect label, echolalic response to the SD, or response that requires a verbal prompt beyond the SD.',
 'most_to_least',
 'Week 1–2: Full echoic prompt (model the word, child repeats before stimulus is presented) → Week 3–4: Partial echoic (first sound only) → Week 5+: 5-second time delay → Independent. Rotate between prompting levels and "known" items to build fluency.',
 '4-step error correction: (1) "My turn" — model the correct tact; (2) Wait 5 seconds; (3) "Your turn" — re-present the stimulus; (4) Reinforce correct response. Immediately follow with a "known" (easy) tact trial before re-probing the target.',
 'Rotate "known" mastered tacts and "unknown" new tacts within each session. Once a tact reaches mastery criterion (3 sessions at 80%+ independent), begin generalization probes. Add new tact targets in groups of 3–5 items per teaching round.',
 'CRF during acquisition (reinforce every correct unprompted tact). Transition to VR2 after mastery, VR3–VR4 for maintenance. Use enthusiastic social praise + tangible reinforcer during acquisition; fade tangible toward social-only as tacting becomes more natural.',
 'Generalize each tact across: 3+ different examples of each item (different pictures, sizes, colors, 3D vs. 2D), 3+ settings, and 3+ different adults. Include naturalistic tact opportunities during play, book-reading, and daily routines.',
 'Monthly maintenance probes on all mastered tacts. Re-teach any item below 80%. Add new tact targets weekly. Expand tacting to include actions, adjectives, and prepositions as the repertoire grows.'),

-- ── LISTENER RESPONDING ───────────────────────────────────────────────────────
('Listener Responding',
 'Discrete trial format — record correct (C), incorrect (I), or prompted (P) per trial. Minimum 20 trials per session. Calculate % correct from array of 4+ items. Mastery: 90%+ independent over 3 consecutive sessions.',
 'Basic visual attention (can scan a 2-item array); sits with therapist for structured sessions; some joint attention; responds to name at least 50% of the time.',
 'Objects or pictures for discrimination arrays (start with 2 items, increase to 4–8). Common items: toys, body part pictures, family member photos, food items, household objects. Organized in categories for curriculum planning.',
 '"Show me ___" / "Touch ___" / "Find ___" / "Point to ___" — said once per trial at natural volume. Present from an array of items. Rotate array positions randomly to prevent position learning.',
 'Child selects, touches, or points to the correct item from the array within 5 seconds after the SD, without additional prompts. Response must be clearly discriminative (not scrolling through options).',
 'Selects wrong item, scrolls through all items before selecting, no response within 5 seconds, or requires a prompt beyond the initial SD.',
 'most_to_least',
 '1. Full physical guidance (hand-over-hand to correct item) → 2. Partial physical (tap correct hand) → 3. Gestural (point to correct item) → 4. Gaze shift toward correct item → 5. Independent. Fade across sessions systematically.',
 '(1) Remove stimuli; (2) Provide physical guidance to correct item; (3) Label the correct item ("That is the ___"); (4) Re-present trial with physical guidance; (5) Reinforce; (6) Insert one "known" easy trial; (7) Re-present target without prompt.',
 'Rotate items in array to prevent position learning. Systematically increase array size: 2 → 4 → 6 → 8 items. Vary position of target randomly. After DTT mastery, introduce naturalistic listener training during daily activities.',
 'CRF during acquisition. VR2 after mastery. Primary reinforcer (tangible) during early acquisition; fade to social praise (thumbs up, high-five, "nice job!") as skills strengthen.',
 'Test with novel examples of each category, different pictures, and different 3D objects. Generalize to natural environment (identify items during snack, dressing, play). Generalize across 3+ adults and 3+ settings.',
 'Monthly probes of all mastered listener discriminations. Re-teach if below 90%. Embed maintenance trials in daily routines (snack time, dressing, play, transitions).'),

-- ── VP/MTS ────────────────────────────────────────────────────────────────────
('VP/MTS',
 'Record correct (C), incorrect (I), prompted (P) on each trial. Track accuracy across matching types separately (identical objects, identical pictures, picture-to-object, non-identical). Mastery: 90%+ for 3 consecutive sessions.',
 'Visual attention to objects (30+ seconds); adequate fine motor skills (reaches for and grasps objects); basic sitting tolerance; some response to adult-delivered instructions.',
 'Matching sets of identical objects, identical pictures, object-to-picture. Inset puzzles, form balls, matching card sets, 3D shape sorters, figurine pairs. Common reinforcing items that come in identical pairs (toy cars, animals, characters).',
 '"Match" / "Put with same" / "Find the same." For puzzles: partially completed puzzle presented. For MTS: sample object presented, child selects match from array.',
 'Child independently selects or places the correct matching item within 5 seconds. For shape sorters/puzzles: completes the placement correctly.',
 'Selects a non-matching item, no response within 5 seconds, requires physical prompt, or places item in wrong location.',
 'most_to_least',
 '1. Full physical (hand-over-hand placement of sample and match) → 2. Partial physical (wrist guidance after child reaches) → 3. Gestural (point to correct match) → 4. Positional prompt (place correct match closest to child) → 5. Independent. Fade systematically over 5-session blocks.',
 'Remove materials. Pause 5 seconds. Re-present with physical guidance to correct match. Reinforce immediately. Use errorless teaching during initial acquisition to build confidence.',
 'Progress through skill sequence: identical objects → non-identical objects (same category) → picture-to-picture → picture-to-object → non-identical cross-category matching. Increase array size progressively (2 → 4 → 6 items).',
 'CRF during acquisition. VR2 once mastered. Tangible + social reinforcement during acquisition; fade to social praise for maintenance.',
 'Generalize matching across multiple examples of each category. Include matching in daily routines: sorting laundry by color, matching socks, sorting toys by type, organizing shapes. Vary materials regularly.',
 'Monthly probes across all mastered matching levels. Embed matching practice in classroom and home activities. Track progression across increasing array sizes and matching complexity.'),

-- ── INDEPENDENT PLAY ─────────────────────────────────────────────────────────
('Independent Play',
 'Time-based measurement — record duration of independent appropriate play during a 30-minute observation. Use interval recording (every 5 minutes). Target: at least 10 continuous minutes of appropriate independent play per 30-minute session.',
 'Basic object manipulation; visual attention to objects for 30+ seconds; some tolerance for non-adult attention; no severely competing self-stimulatory behaviors during play.',
 'Age-appropriate toys identified as preferred through preference assessment: cause-and-effect toys, construction toys (blocks, LEGO), manipulatives, puzzles, books, art supplies. Rotate materials to maintain novelty.',
 'Natural environment arrangement — preferred toys available and accessible in play area. Therapist withdraws to observe. Minimal verbal prompts. Target is for the MO (interest in play) to become the primary controlling variable.',
 'Child independently engages with toy or activity in an appropriate, functional manner for the target duration without adult prompts or reinforcement delivery.',
 'Leaves play area, engages in self-stimulatory behavior with toys (scripting, spinning, lining up), seeks adult attention repeatedly, or stops playing before target duration.',
 'least_to_most',
 '1. No prompt — observe for 30 seconds → 2. Gestural (point to toy) → 3. Verbal prompt ("Play with the ___") → 4. Model correct play and withdraw → 5. Physical guidance (place child''s hands on toy). Use least-intrusive prompt; fade from more to less support.',
 'Brief, neutral redirect: move child toward appropriate play with minimal verbal contact. Model appropriate play for 10 seconds and immediately withdraw. Avoid providing excessive adult attention for off-task behaviors (may reinforce off-task).',
 'Begin with 2 minutes of independent play target, increase by 1 minute every 3 sessions once target is met. Gradually fade adult proximity (nearby → across room → out of sight → checking in periodically). Introduce novel toys systematically.',
 'Check-in reinforcement every 2–3 minutes during play initially (brief praise for continued play). Thin to end-of-session reinforcement. Allow naturally reinforcing play activities to develop — the play itself should become reinforcing.',
 'Generalize across 3+ settings (therapy room, home bedroom, classroom free time), 5+ different types of play activities, and with adult at varying distances and positions. Program for free play across daily routines.',
 'Monthly play observations. Add new play activities to maintain repertoire breadth. Conduct booster sessions if independent play duration drops below target for 2+ consecutive observations.'),

-- ── SOCIAL BEHAVIOR ──────────────────────────────────────────────────────────
('Social Behavior',
 'Frequency and duration counts of targeted social behaviors (eye contact, initiations, responses to peers, turn-taking). Observe in 30-minute structured play session with peers. Use partial-interval recording for social engagement.',
 'Basic attention to people; responds to own name 80%+ of the time; some play skills; a functional mand repertoire; tolerates physical proximity of peers without distress.',
 'Preferred toys and activities for peer interaction; structured turn-taking games; social stories targeting specific skills; visual supports (visual turn cards, "my turn" / "your turn" indicators). Peers identified as appropriate play partners.',
 'Natural social environment with peers available and engaged in preferred activities. Peer or adult social approach, invitation, or play opportunity. Therapist may arrange social opportunities but minimizes directing the interaction.',
 'Child engages in the target social behavior (eye contact, turn-taking, sharing, greeting, following peer''s play) within 5 seconds of the social opportunity, without adult prompting.',
 'Ignores peer, walks away, engages in self-stimulatory behavior, protests interaction, or requires adult prompting to engage.',
 'least_to_most',
 '1. Wait 5 seconds for spontaneous social behavior → 2. Verbal prompt ("Look at your friend" / "It''s your turn") → 3. Model the social behavior with another adult or peer confederate → 4. Physical guidance. Fade prompts over sessions.',
 'Provide least-restrictive prompt needed to produce the behavior. Reinforce any approximation of the target social behavior. Avoid excessive correction that may make social interactions aversive. Re-create the social opportunity if needed.',
 'Begin with 1:1 adult–child social interaction. Progress to: 1 peer + 1 adult → 2 peers + 1 adult → small group (3–4 children) → naturalistic peer group. Use embedded social opportunities throughout all daily activities.',
 'CRF for all social initiations during acquisition. VR3 for response behaviors. Use enthusiastic social reinforcement (cheering, high-fives) and tangible if needed. Thin tangible reinforcement gradually — social interaction itself should become the reinforcer.',
 'Generalize across 3+ familiar peers, 3+ settings (classroom, playground, therapy room, home, community), and multiple social activity types. Conduct social skills group sessions at least twice weekly.',
 'Monthly naturalistic observation probes. Continue peer pairing in all settings. Monitor social reciprocity and relationship quality. Social behavior is naturally maintained through peer interactions — build genuine friendships.'),

-- ── MOTOR IMITATION ──────────────────────────────────────────────────────────
('Motor Imitation',
 'Record correct (C), incorrect (I), prompted (P) on each imitation trial. Target: 80%+ independent over 3 consecutive sessions. Track separately by action type: gross motor, fine motor, object manipulation.',
 'Visual attention to modeled actions for 3+ seconds; some basic motor coordination; tolerates physical prompting; basic attending skills.',
 'Age-appropriate objects for object imitation: maracas, rhythm sticks, drum, blocks, stacking rings, play dough, ball. Open space for gross motor imitations. No materials needed for pure body movement imitation.',
 'Therapist says "Do this" and immediately models the target motor action. No additional verbal description of the action. Ensure child is attending before modeling.',
 'Child imitates the motor action within 5 seconds, independently (without physical prompt). Approximations are accepted during early acquisition if they are clearly discriminative from other trained actions.',
 'Different motor action from model, partial imitation that does not match key features, no response within 5 seconds, or requires physical prompt.',
 'most_to_least',
 '1. Full physical (hand-over-hand during or immediately after model) → 2. Partial physical (light touch to initiate movement) → 3. Gestural (point to relevant body part) → 4. Re-model (repeat the action) → 5. Independent. Fade physical to gestural to independent over 5-session blocks.',
 'Immediately following incorrect response: re-model the action, provide physical guidance to complete it correctly, reinforce correct imitation with enthusiastic praise + tangible. Then re-present the same action without prompt.',
 'Maintain a rotating set of 5–10 known actions. Introduce 1–2 novel actions per week using "probe then teach" format. Once a full repertoire of 15+ actions is mastered, begin using imitation in functional contexts (crafts, games, songs).',
 'CRF during acquisition. VR3 after mastery. Enthusiastic social praise + tangible reinforcers during acquisition; fade to social praise only as imitation repertoire grows.',
 'Generalize imitation across 3+ adults (therapist, parent, teacher), varied settings, and across action categories (body movements, object use, gross motor). Include peer imitation opportunities during group activities and games.',
 'Monthly probes of entire imitation repertoire. Add novel actions regularly. Integrate motor imitation into group activities, PE, music, art, and play.'),

-- ── ECHOIC ────────────────────────────────────────────────────────────────────
('Echoic',
 'Record correct (C), incorrect (I), prompted on each echoic trial. Mastery: 80%+ correct across 5 consecutive sessions. Track at phoneme, syllable, and word levels. Use EESA scoring for formal assessment of echoic repertoire.',
 'Attends to speaker''s voice for 2+ seconds; has some vocal behavior (even vocalizations or babbling); is not severely non-vocal; can sit with an adult for brief teaching sessions.',
 'EESA protocol materials (if using formal assessment); picture cards to pair echoic training with visual context; no specific physical materials needed — primarily vocal interaction and reinforcer delivery.',
 'Therapist says "Say ___" and immediately models the target word or sound at normal volume and rate. May pair with a picture for context (show picture, then model the word). One model per trial.',
 'Child repeats the target word or sound accurately (or with an acceptable approximation that is distinctly different from other trained sounds) within 3 seconds.',
 'No response within 3 seconds, incorrect phoneme pattern, repetition of non-target vocalization, or echoing the wrong portion of the SD.',
 'most_to_least',
 'Start with the simplest sounds (vowels, bilabial consonants: /m/, /b/, /p/) and build complexity. Use shaping: reinforce successive approximations toward the target form. Pair with visual articulation cues (show mouth position) for children who need added support. Build from single sounds → CV syllables → CVC words → multisyllabic words.',
 'Immediately re-model the target sound or word. Accept and reinforce the best available approximation. Do not correct in a punitive manner. Run multiple brief blocks (5–10 trials). Keep echoic training highly positive.',
 'Use echoic skills to transfer to tact and mand training. Once echoic for a word is established, immediately begin fading echoic prompts in tact trials. Build the bridge from echoic to other verbal operants (tact, mand, intraverbal).',
 'CRF for all correct echoic responses. Maintain a high rate of reinforcement to keep echoic behavior strong. Deliver reinforcement immediately and enthusiastically.',
 'Generalize echoic skills across multiple adults, vary vocal volume and rate of model, vary contextual settings. Build echoic repertoire to support expansion of all other verbal operants.',
 'Embed echoic opportunities throughout daily activities and transitions. Continue EESA progress monitoring monthly. Use echoic training to bridge to new mand and tact targets as vocabulary grows.'),

-- ── LRFFC ────────────────────────────────────────────────────────────────────
('LRFFC',
 'Discrete trial format — record C/I/P per trial. Minimum 20 trials per session. Calculate % correct from array of 4+ items. Mastery: 90%+ independent over 3 consecutive sessions. Track by type: function, feature, and class separately.',
 'Listener Responding Level 2+ (selects from array of 4); Tact repertoire of 50+ items; basic categorization skills; some familiarity with functional use of common objects.',
 'Array of 4–8 pictures or objects from multiple categories; LRFFC teaching sets organized by function (what we use it for), feature (what it looks/sounds/feels like), and class (what category it belongs to). Common categories: animals, vehicles, clothing, food, tools, furniture.',
 '"Find one that is ___" (feature) / "Find something we ___" (function) / "Find another ___" (class). Present from array of 4+ items. One SD per trial.',
 'Child selects the correct item from the array within 5 seconds based on the stated function, feature, or class — without the item''s name being used in the SD.',
 'Selects wrong item, selects by label rather than function/feature/class, no response within 5 seconds, or requires verbal cues beyond the SD.',
 'most_to_least',
 '1. Full physical (guide hand to correct item after SD) → 2. Gestural (point to correct item) → 3. Partial verbal cue ("It has ___" or "We use it to ___") → 4. Independent. Vary prompt level systematically across sessions.',
 'Point to the correct item and name the relevant function, feature, or class. Re-present the trial with a gestural prompt. Reinforce correct response. Immediately re-probe without any prompt.',
 'Begin with a single attribute type (e.g., function only for all targets). Once mastered, add feature targets, then class targets. Rotate examples within each category. Transition to naturalistic LRFFC questions during daily activities.',
 'CRF during acquisition. VR3 after mastery criterion met. Social praise as primary reinforcer; tangible on VR5 schedule after strong responding is established.',
 'Generalize across different examples within each category. Use novel items in probe trials. Practice in natural contexts (cooking: "find something we use to stir"; grooming: "find something that keeps you warm"; community: "find something that goes fast").',
 'Monthly maintenance probes. Continue embedding LRFFC questions throughout daily activities and across settings. Include LRFFC in conversational interactions as intraverbal skills develop.'),

-- ── INTRAVERBAL ──────────────────────────────────────────────────────────────
('Intraverbal',
 'Record correct (C), incorrect (I), prompted (P) per trial. Target: 80%+ independent over 3 consecutive sessions. Track by category type: fill-ins, category questions, social questions, WH-questions.',
 'Tact repertoire of 50+ items; listener responding for 25+ items; basic category knowledge; functional echoic repertoire to echo and then fade prompts.',
 'Visual category cards for initial teaching only (faded quickly); topic cards for structured conversation practice; no physical materials needed once the skill is established.',
 'Verbal antecedent only — no visual support. Example SDs: "You eat with a ___", "What sound does a cow make?", "Name something you see at the zoo", "What do you do when you are cold?" — one verbal prompt per trial.',
 'Child provides an accurate intraverbal response within 5 seconds, without requiring visual cues or echoic/partial prompts.',
 'No response within 5 seconds, echolalic response to the SD, incorrect answer, or response that requires a verbal prompt beyond the SD.',
 'most_to_least',
 '1. Full verbal model (say the answer, child repeats — then fade to intraverbal) → 2. Partial verbal prompt (first syllable/sound of the answer) → 3. 5-second time delay → 4. Independent. Always fade systematically toward independence.',
 'Provide full verbal model of correct answer; child repeats; reinforce. Then present at least 3 "known" intraverbals. Re-probe target without prompt. Avoid repeating the trial with the error response.',
 'Start with fill-ins (easiest: "You eat soup with a ___"), progress to WH-questions ("What do you eat with?"), then 2-step ("Name two animals"), then category questions. Use visual supports only during initial acquisition and fade quickly.',
 'CRF initially. VR3 once mastered. Thin toward natural social reinforcement (conversational back-and-forth, enthusiastic engagement as reinforcer).',
 'Practice intraverbals with multiple people, across settings, and at varied times throughout the day. Include intraverbal opportunities in all daily routines: car rides, meals, bath time, play.',
 'Monthly maintenance probes of all mastered intraverbal targets. Embed intraverbal practice in all daily interactions. Add new intraverbal topics as child''s language grows. Bridge to spontaneous conversational intraverbal use.'),

-- ── CLASSROOM ROUTINES ────────────────────────────────────────────────────────
('Classroom Routines',
 'Interval recording during group activities — record on-task/off-task every 5 minutes during a 30-minute session. Also record number of group instructions followed independently (frequency count). Target: 80%+ on-task intervals and 90%+ instruction-following.',
 'Basic listener responding for 20+ items; can sit with adult for 5+ minutes in 1:1; some joint attention; tolerates classroom environment without severe escape/avoidance behavior.',
 'Typical classroom materials (worksheets, art supplies, books, pencils, scissors); visual daily schedule; transition supports (first-then board); group activity materials. Reinforcer inventory for classroom-appropriate reinforcers.',
 'Natural classroom instruction given to the group: "Take out your worksheet", "Line up at the door", "Sit in your seat", "Open your book to page ___." Wait 5 seconds for independent response after group instruction.',
 'Child follows the group instruction within 5 seconds, independently, matching the behavior of peers. No individualized prompt needed.',
 'Does not respond, engages in off-task or disruptive behavior, requires individual prompting, or leaves the group activity.',
 'least_to_most',
 '1. Group instruction only — wait 5 seconds → 2. Repeat instruction while standing near child → 3. Gesture or visual cue (point to correct location/materials) → 4. Individual verbal prompt → 5. Physical guidance. Use minimum prompt needed to maintain independence.',
 'Minimal, least-intrusive correction to avoid disrupting the group. Brief, calm redirect; physical guidance only if necessary. Reinforce immediately when the correct behavior occurs. Avoid extended 1:1 correction in group settings.',
 'Begin 1:1 training for each target routine. Then introduce in small group (2–3 children). Then expand to full class. Use visual supports (visual schedule, first-then boards) and fade gradually. Coordinate with classroom staff.',
 'Use group contingencies (class token economy, group praise) where appropriate. Thin to natural classroom reinforcement (teacher praise, preferred activities, earned free time). Avoid excessive individualized reinforcement that stands out from peers.',
 'Practice target routines in multiple classroom settings (homeroom, PE, lunch, specials). Coordinate with all classroom staff for consistent expectations. Include home generalization targets aligned with school routines.',
 'Monthly classroom observation (naturalistically conducted). Coordinate with classroom teacher for ongoing monitoring. Embed classroom routines in daily schedule permanently. Fade paraprofessional support as independence increases.'),

-- ── LINGUISTIC STRUCTURE ──────────────────────────────────────────────────────
('Linguistic Structure',
 'Collect 50-utterance language sample monthly. Measure MLU (mean length of utterance) and morpheme use. Record specific grammatical targets in structured tasks (C/I per trial). Mastery: 80%+ correct use of target structure over 3 sessions.',
 'Tact and mand repertoire of 50+ items; basic conversational skills; MLU of 2+ morphemes; some use of pronouns and prepositions; functional verbal communication established.',
 'Storybooks and picture books with varied sentence structures; picture description cards; structured language activities targeting specific grammar forms; conversation starters. SLP collaboration recommended.',
 'Naturalistic opportunities: activities that elicit target grammatical forms (e.g., action pictures for -ing verbs, possession cards for possessives). Structured: "Tell me about the picture", "What is he doing?", "Whose ___ is it?" Target one grammatical structure per teaching block.',
 'Child produces the target grammatical structure (e.g., present progressive, plural -s, possessive, pronouns) spontaneously or in response to a conversational prompt, within a natural response time.',
 'Uses incorrect grammar, omits the target morpheme, uses an earlier-stage structure, or does not produce a response.',
 'least_to_most',
 '1. Wait for spontaneous production (0–5 seconds) → 2. Open-ended conversational prompt ("Tell me more") → 3. Cloze/fill-in prompt ("He is ___ing") → 4. Recast after child''s attempt (natural modeling) → 5. Full model. Use minimal prompting to maintain natural communicative exchange.',
 'Use recasting: after child produces an incorrect grammatical form, naturally restate with correct grammar without drawing attention to the error ("Oh, you mean he is running!"). Do not say "wrong" or "try again." Recreate the eliciting condition.',
 'Practice target grammar in structured activities first (picture description, structured games), then fade to naturalistic conversation. Coordinate with SLP for generalization across therapy contexts.',
 'Natural social reinforcement (enthusiastic conversational response, expand on child''s utterance). Add specific reinforcement only if needed to maintain participation. Avoid making grammatical targets feel like a test.',
 'Generalize target grammatical forms across all daily conversations, multiple people, and settings. Coordinate with parents for home practice. SLP consultation recommended for complex linguistic targets.',
 'Monthly language sampling to track MLU and grammatical accuracy. Continue building linguistic complexity toward age-appropriate grammar. Adjust targets as developmental norms advance.'),

-- ── READING ───────────────────────────────────────────────────────────────────
('Reading',
 'Record accuracy (% correct) on target reading skills per session from 10-item probes. Track by skill level: letter ID, sight words, decoding (CVC → multisyllabic), fluency (words per minute), and comprehension. Mastery: 90%+ independent over 3 sessions.',
 'VP/MTS Level 3+ (matching letters and words); basic tact repertoire; listener responding for letter names; adequate visual tracking from left to right; basic sitting tolerance for academic tasks.',
 'Alphabet cards, phonics program materials (decodable books matched to current level), sight word flashcards, leveled readers, picture books for comprehension. Highlighters and tracking tools for scanning support.',
 '"What letter is this?" (letter ID) / "Read the word" (sight words/decoding) / "Read the sentence" (fluency) / "What happened first in the story?" (comprehension). Vary SD complexity to match current reading level.',
 'Child reads the letter, word, sentence, or passage accurately within 5 seconds (or within age-appropriate reading rate for fluency targets).',
 'Incorrect sound/word identification, no response within 5 seconds, skipping words without self-correcting, or requiring prompts beyond the initial SD.',
 'most_to_least',
 'Phonics/decoding: sound-by-sound blending prompt → partial sound (first phoneme) → independent. Sight words: full echoic model → partial echoic → 5-second time delay → independent. Comprehension: visual supports (graphic organizer) → guiding questions → independent answer.',
 'For decoding errors: model each phoneme, then blend together with child. For sight words: immediate echoic model, child repeats, re-present. For comprehension: reread the relevant passage, point to key details, guide with WH-questions.',
 'Begin with isolated flashcard level, move to word in a simple sentence, move to word in a paragraph, move to independent reading of decodable books. Match book reading level to current decodable patterns mastered.',
 'Social praise for reading attempts and successes. Token economy for completing reading tasks. Preferred reading materials as reinforcers. Thin contrived reinforcement as reading itself becomes reinforcing.',
 'Practice reading across materials: books, environmental print (signs, menus, labels). Include functional reading in daily life. Coordinate with school reading curriculum. Build reading fluency with home reading practice.',
 'Daily reading practice at home and at school. Monthly reading assessments (accuracy and fluency). Build fluency through repeated reading of known texts. Advance to next reading level after mastery is confirmed.'),

-- ── WRITING ───────────────────────────────────────────────────────────────────
('Writing',
 'Record accuracy per trial (letter formation, word copying, sentence writing). Calculate % correct per session. Track progression: imitation (tracing) → copying → independent recall. Mastery: 90%+ legible production over 3 consecutive sessions.',
 'Adequate fine motor skills for pencil control; ability to imitate gross motor movements; basic letter/number discrimination; visual attention to written models.',
 'Pencils, crayons, markers, crayon grips or pencil grips if needed; lined and unlined paper; letter formation guides with directional arrows; name card for reference; dry-erase whiteboards; dot-to-dot tracing worksheets.',
 '"Write your name" / "Copy this word" / "Write the letter ___" / "Finish the sentence." Present a written model on paper or whiteboard, or give a verbal dictation for more advanced targets.',
 'Child produces a legible letter, word, or sentence with correct letter formation, appropriate size, and proper spacing, independently within natural writing time.',
 'Illegible formation, incorrect letter, significant reversal, requires physical guidance, or significantly distorted beyond developmental expectations.',
 'most_to_least',
 '1. Full physical (hand-over-hand writing) → 2. Partial physical (light wrist or finger guidance) → 3. Tracing a dotted letter/word model → 4. Copying from a visible model → 5. Independent recall and writing. Fade systematically over sessions.',
 'Pause writing. Provide neutral verbal cue ("Check your ___"). Re-present with appropriate prompt level (one step up). For persistent letter reversals, use directional arrows taped to the desk or tactile cues.',
 'Begin with name and most-needed words (functional writing first). Progress: high-frequency sight words → curriculum-relevant words → sentence writing → independent composition. Practice each at tracing level before copying, copying before independent.',
 'Praise effort and any improvement in legibility. Allow access to preferred writing tools (gel pens, colored markers) as reinforcers. Use a writing achievement chart. Connect to meaningful topics child is interested in.',
 'Practice writing across all school subjects and daily contexts (labeling drawings, grocery lists, greeting cards). Consult OT if persistent fine motor challenges are observed. Coordinate with classroom writing curriculum.',
 'Daily writing practice. OT consultation for handwriting issues if needed. Monthly assessment of writing fluency and legibility. Expand writing targets as skills develop (sentences → paragraphs → stories).'),

-- ── MATH ──────────────────────────────────────────────────────────────────────
('Math',
 'Daily math probes — record correct (C), incorrect (I) per problem (10–20 problems). Calculate % correct and fluency (correct digits per minute) for applicable skills. Mastery: 90%+ over 3 consecutive sessions.',
 'One-to-one correspondence; ability to match quantities to numerals (1–5 initially); basic listener responding for number names; VP/MTS for numeral matching; rote counting to 10.',
 'Manipulatives: counting bears, blocks, coins, chips, number tiles; number cards 1–20; number line; base-10 blocks for place value; 100s chart; abacus; dice; math worksheets; calculator for checking work on advanced skills.',
 '"How many?" (counting objects) / "Count the ___" / "What is ___ + ___?" / "Write the number ___" / "Which is more?" — vary by current math concept being targeted. Present problems in vertical and horizontal formats for operations.',
 'Child produces the correct numerical answer or performs the correct math operation within 10 seconds (or within a specified time limit for fluency targets).',
 'Incorrect numerical answer, counting error (skip counting, double counting), no response, or clearly random guess without strategy.',
 'most_to_least',
 '1. Full physical (hand-over-hand guidance through counting/writing) → 2. Partial physical (point to first item to start counting) → 3. Gestural (point to manipulatives or number line) → 4. Verbal cue ("Count them" or "Use your fingers") → 5. Independent. Fade from concrete to abstract systematically.',
 'Immediately redo with manipulatives. Model the correct counting/computation process step-by-step. Have child repeat the process independently. For counting errors, restart the count from the beginning.',
 'Concrete (manipulatives) → Representational/Pictorial (pictures of objects to count) → Abstract (numerals only). Build fact fluency through daily timed practice after conceptual understanding is established.',
 'Praise correct mathematical thinking, not just correct answers. Math sticker chart or token economy. Connect math success to preferred activities (e.g., earn tokens toward preferred item).',
 'Integrate math into daily routines: counting snacks, setting the table, telling time, using money in community settings. Coordinate with classroom math curriculum. Include functional math skills (shopping, measuring).',
 'Daily math fact practice (flashcards or digital). Monthly benchmark assessments aligned with grade-level standards. Use spaced retrieval practice for maintenance of mastered arithmetic facts.'),

-- ── SPELLING ──────────────────────────────────────────────────────────────────
('Spelling',
 'Weekly spelling probes — record accuracy per word (correct = all letters in correct sequence). Calculate % correct. Mastery: 90%+ over 3 consecutive weekly probes. Also track writing fluency (correct letters per minute) for advanced learners.',
 'Letter identification (all 26 letters, upper and lowercase); basic phoneme awareness (identifying initial sounds); some reading decoding ability; ability to copy words accurately.',
 'Letter tiles or magnetic letters; spelling flashcards with word + picture; dry-erase board for writing practice; spelling workbook; look-say-cover-write-check worksheets; audio recording for dictation practice.',
 '"Spell ___" (verbal dictation) / "Write the word ___" / Point to a picture and say "Write the name of this." One word per trial. Present in isolation first, then in sentence context for generalization.',
 'Child writes or selects all letters of the target word in the correct sequence, independently, within natural writing time.',
 'Incorrect letter(s), letters in wrong sequence, omission of letters, addition of incorrect letters, or significant reversal of letter order.',
 'most_to_least',
 '1. Copy from full visual model (word written clearly nearby) → 2. Copy from memory (model presented then removed) → 3. Partial prompt (first letter provided) → 4. Verbal segmentation support ("Say it slowly: b-a-t") → 5. Independent recall.',
 'Show the correct spelling immediately. Have child trace or copy the correct version. Then attempt independently. Use look-say-cover-write-check for immediate self-correction. Provide phonics support for decodable words (segment the word into phonemes).',
 'Begin with highest-frequency sight words (Dolch or Fry lists), then phonetically regular CVC words, then content-area words. Practice each word at copy level before independent. Generalize to use in sentences and functional writing.',
 'Praise correct spelling. Use spelling achievement chart to track progress. Celebrate mastery of word lists with preferred rewards. Connect to classroom spelling tests for natural reinforcement.',
 'Include spelling in all writing activities daily. Connect to reading: words mastered in reading should also be practiced in spelling. Use spelling in all functional writing tasks (labels, notes, worksheets).',
 'Regular review of mastered word lists (at least monthly). Integrate spelling into daily writing practice. Use spaced retrieval practice for long-term retention. Coordinate with classroom spelling curriculum.');
