import { IntakeStep } from './types';

export const intakeSteps: IntakeStep[] = [
  {
    id: 1,
    fieldName: 'childAge',
    question: "How old is your child?",
    type: 'single-select',
    options: [
      'Under 2',
      '2–3 years',
      '4–5 years',
      '6–8 years',
      '9–12 years',
      '13 or older',
    ],
  },
  {
    id: 2,
    fieldName: 'diagnosedBy',
    question: "Who diagnosed your child?",
    type: 'single-select',
    options: [
      'Developmental pediatrician',
      'Psychiatrist',
      'Psychologist',
      'School evaluation team',
      'Not officially diagnosed yet',
    ],
  },
  {
    id: 3,
    fieldName: 'diagnoses',
    question: "What was your child diagnosed with?",
    subtitle: "Select all that apply — it's okay if you're unsure of some terms.",
    type: 'multi-select',
    options: [
      'Autism Spectrum Disorder (ASD)',
      'ADHD',
      'Speech/Language Delay',
      'Sensory Processing Disorder',
      'Intellectual Disability',
      "I'm not sure of the exact terms",
    ],
  },
  {
    id: 4,
    fieldName: 'currentSupport',
    question: "Is your child currently receiving any therapy or support?",
    type: 'multi-select',
    options: [
      'No, nothing yet',
      'Speech therapy (SLP)',
      'ABA therapy',
      'Occupational therapy (OT)',
      'Early intervention services',
      'Special education services (IEP/IFSP)',
    ],
  },
  {
    id: 5,
    fieldName: 'topConcerns',
    question: "What are you most concerned about right now?",
    subtitle: "Pick up to 3.",
    type: 'multi-select',
    maxSelections: 3,
    options: [
      "I don't know where to start",
      'Finding the right therapist',
      'Understanding insurance coverage',
      "My child's communication",
      "My child's behavior at home",
      'School and education planning',
      'Connecting with other parents',
      'My own stress and wellbeing',
    ],
  },
  {
    id: 6,
    fieldName: 'freeText',
    question: "Anything else you'd like to share about your child or situation?",
    subtitle: "This is optional. The more context you give, the more specific your next steps will be.",
    type: 'textarea',
    optional: true,
    placeholder: "e.g. My son was just diagnosed last week, he's mostly nonverbal and we're completely new to this...",
  },
];
